#!/usr/bin/env python3
"""
Script to visualize Knowledge Graph from pickle files

This script loads the graph pickle file generated by build_kg_mimic.py
and creates visualizations showing:
- Node types (ICD9, CPT, ATC, LAB) with different colors
- Edge types (hierarchical, cooccurrence, augmented) with different styles
- Graph structure and layout
"""

import os
import pickle
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from collections import Counter
import argparse


class GraphVisualizer:
    def __init__(self, graph_file, vocab_file=None, vocab_info_file=None):
        """
        Initialize Graph Visualizer
        
        Args:
            graph_file: Path to graph pickle file
            vocab_file: Path to graphnode_vocab.pkl (optional)
            vocab_info_file: Path to vocab_info.pkl (optional)
        """
        self.graph_file = graph_file
        self.vocab_file = vocab_file
        self.vocab_info_file = vocab_info_file
        self.G = None
        self.graphnode_vocab = None
        self.vocab_info = None
        
    def load_graph(self):
        """Load graph from pickle file"""
        print(f"Loading graph from {self.graph_file}...")
        with open(self.graph_file, 'rb') as f:
            self.G = pickle.load(f)
        print(f"Graph loaded: {self.G.number_of_nodes()} nodes, {self.G.number_of_edges()} edges")
        
        if self.vocab_file and os.path.exists(self.vocab_file):
            print(f"Loading vocab from {self.vocab_file}...")
            with open(self.vocab_file, 'rb') as f:
                self.graphnode_vocab = pickle.load(f)
        
        if self.vocab_info_file and os.path.exists(self.vocab_info_file):
            print(f"Loading vocab info from {self.vocab_info_file}...")
            with open(self.vocab_info_file, 'rb') as f:
                self.vocab_info = pickle.load(f)
    
    def get_node_statistics(self):
        """Get statistics about nodes"""
        node_types = [self.G.nodes[node].get('type', 'UNKNOWN') for node in self.G.nodes()]
        type_counts = Counter(node_types)
        
        edge_types = [self.G.edges[edge].get('edge_type', 'unknown') for edge in self.G.edges()]
        edge_type_counts = Counter(edge_types)
        
        return type_counts, edge_type_counts
    
    def print_statistics(self):
        """Print graph statistics"""
        print("\n" + "=" * 80)
        print("Graph Statistics")
        print("=" * 80)
        
        node_types, edge_types = self.get_node_statistics()
        
        print(f"\nTotal nodes: {self.G.number_of_nodes()}")
        print(f"Total edges: {self.G.number_of_edges()}")
        
        print("\nNode types:")
        for node_type, count in sorted(node_types.items()):
            print(f"  {node_type}: {count}")
        
        print("\nEdge types:")
        for edge_type, count in sorted(edge_types.items()):
            print(f"  {edge_type}: {count}")
        
        # Degree statistics
        degrees = [self.G.degree(node) for node in self.G.nodes()]
        print(f"\nDegree statistics:")
        print(f"  Min degree: {min(degrees)}")
        print(f"  Max degree: {max(degrees)}")
        print(f"  Average degree: {np.mean(degrees):.2f}")
        print(f"  Median degree: {np.median(degrees):.2f}")
        
        if self.vocab_info:
            print("\nVocabulary sizes:")
            for vocab_type, vocab_list in self.vocab_info.items():
                print(f"  {vocab_type.upper()}: {len(vocab_list)}")
    
    def get_relationships(self):
        """Extract relationships between different node types"""
        relationships = {
            'ICD9-ATC': [],
            'ICD9-LAB': [],
            'ICD9-CPT': [],
            'ATC-LAB': [],
            'ATC-CPT': [],
            'LAB-CPT': [],
            'ICD9-ICD9': []
        }
        
        # Helper to get node code/name with prefix
        def get_node_display(node):
            node_type = self.G.nodes[node].get('type', 'UNKNOWN')
            
            # Try to get from graphnode_vocab first
            code_str = None
            if self.graphnode_vocab:
                if node in self.graphnode_vocab:
                    code_str = str(self.graphnode_vocab[node])
            # Then try from node attribute
            if not code_str:
                code = self.G.nodes[node].get('code', None)
                if code:
                    code_str = str(code)
                else:
                    code_str = str(node)
            
            # Add prefix based on node type for better identification
            if node_type == 'ICD9':
                if not code_str.startswith('ICD') and not code_str.endswith('_ROOT'):
                    return f'ICD_{code_str}'
            elif node_type == 'LAB':
                if not code_str.startswith('LAB') and not code_str.endswith('_ROOT'):
                    return f'LAB_{code_str}'
            elif node_type == 'CPT':
                if not code_str.startswith('CPT') and not code_str.startswith('DRUG'):
                    return f'CPT_{code_str}'
            elif node_type == 'ATC':
                if not code_str.startswith('DRUG') and not code_str.startswith('ATC'):
                    return f'ATC_{code_str}'
            
            return code_str
        
        for u, v, data in self.G.edges(data=True):
            u_type = self.G.nodes[u].get('type', 'UNKNOWN')
            v_type = self.G.nodes[v].get('type', 'UNKNOWN')
            edge_type = data.get('edge_type', 'unknown')
            weight = data.get('weight', 1.0)
            
            # Skip hierarchical edges (only show co-occurrence and augmented)
            if edge_type == 'hierarchical':
                continue
            
            # Get node display names
            u_display = get_node_display(u)
            v_display = get_node_display(v)
            
            # Sort types for consistent key
            types = sorted([u_type, v_type])
            key = f"{types[0]}-{types[1]}"
            
            if key in relationships:
                relationships[key].append({
                    'node1': u_display,
                    'node2': v_display,
                    'type1': u_type,
                    'type2': v_type,
                    'edge_type': edge_type,
                    'weight': weight
                })
            elif u_type == 'ICD9' and v_type == 'ICD9':
                relationships['ICD9-ICD9'].append({
                    'node1': u_display,
                    'node2': v_display,
                    'type1': u_type,
                    'type2': v_type,
                    'edge_type': edge_type,
                    'weight': weight
                })
        
        return relationships
    
    def print_relationships(self):
        """Print relationships between node types"""
        print("\n" + "=" * 80)
        print("Node Relationships (for Manual Inspection)")
        print("=" * 80)
        
        relationships = self.get_relationships()
        
        for rel_type, rels in relationships.items():
            if len(rels) > 0:
                print(f"\n{rel_type} Relationships ({len(rels)} connections):")
                print("-" * 80)
                # Sort by weight (descending) if available
                rels_sorted = sorted(rels, key=lambda x: x.get('weight', 0), reverse=True)
                for i, rel in enumerate(rels_sorted[:20], 1):  # Show top 20
                    weight_str = f" (weight: {rel['weight']:.2f})" if rel.get('weight', 0) > 1 else ""
                    print(f"  {i}. {rel['node1']} <-> {rel['node2']}{weight_str} [{rel['edge_type']}]")
                if len(rels) > 20:
                    print(f"  ... and {len(rels) - 20} more")
        
        # Summary by type
        print("\n" + "=" * 80)
        print("Relationship Summary")
        print("=" * 80)
        for rel_type, rels in relationships.items():
            if len(rels) > 0:
                print(f"  {rel_type}: {len(rels)} connections")
    
    def create_subgraph(self, max_nodes=500, strategy='random'):
        """
        Create a subgraph for visualization
        
        Args:
            max_nodes: Maximum number of nodes in subgraph
            strategy: 'random', 'high_degree', or 'hierarchical'
        """
        if self.G.number_of_nodes() <= max_nodes:
            return self.G
        
        print(f"\nCreating subgraph with {max_nodes} nodes (strategy: {strategy})...")
        
        if strategy == 'random':
            nodes = np.random.choice(list(self.G.nodes()), size=max_nodes, replace=False)
        elif strategy == 'high_degree':
            degrees = [(node, self.G.degree(node)) for node in self.G.nodes()]
            degrees.sort(key=lambda x: x[1], reverse=True)
            nodes = [node for node, _ in degrees[:max_nodes]]
        elif strategy == 'hierarchical':
            # Get root nodes and their immediate neighbors
            root_nodes = [node for node in self.G.nodes() 
                         if self.G.nodes[node].get('level', 999) == 0]
            nodes = set(root_nodes)
            
            # Add neighbors of root nodes
            for root in root_nodes:
                neighbors = list(self.G.neighbors(root))
                nodes.update(neighbors[:10])  # Limit neighbors per root
            
            # If still not enough, add random nodes
            if len(nodes) < max_nodes:
                remaining = max_nodes - len(nodes)
                other_nodes = [n for n in self.G.nodes() if n not in nodes]
                nodes.update(np.random.choice(other_nodes, size=min(remaining, len(other_nodes)), replace=False))
            
            nodes = list(nodes)
        else:
            nodes = list(self.G.nodes())[:max_nodes]
        
        subgraph = self.G.subgraph(nodes)
        print(f"Subgraph created: {subgraph.number_of_nodes()} nodes, {subgraph.number_of_edges()} edges")
        return subgraph
    
    def visualize_graph(self, output_file='graph_visualization.png', 
                       max_nodes=500, layout='spring', figsize=(20, 16),
                       node_size=50, font_size=8, show_labels=True):
        """
        Visualize the graph
        
        Args:
            output_file: Output image filename
            max_nodes: Maximum nodes to visualize (if graph is too large)
            layout: Layout algorithm ('spring', 'circular', 'kamada_kawai', 'hierarchical')
            figsize: Figure size
            node_size: Size of nodes
            font_size: Font size for labels
            show_labels: Whether to show node labels
        """
        print(f"\nCreating visualization...")
        
        # Create subgraph if needed
        G_viz = self.create_subgraph(max_nodes=max_nodes, strategy='hierarchical')
        
        # Set up figure
        fig, ax = plt.subplots(figsize=figsize)
        
        # Define colors for node types - brighter and more distinct
        node_type_colors = {
            'ICD9': '#E74C3C',      # Bright Red (more visible)
            'CPT': '#1ABC9C',       # Bright Teal (more visible)
            'ATC': '#3498DB',       # Bright Blue (more visible)
            'LAB': '#E67E22',       # Bright Orange (more visible)
            'UNKNOWN': '#95A5A6'    # Gray
        }
        
        # Define colors for edge types
        edge_type_colors = {
            'hierarchical': '#2C3E50',      # Dark blue-gray
            'cooccurrence': '#E74C3C',      # Red
            'augmented': '#9B59B6',         # Purple
            'unknown': '#BDC3C7'            # Light gray
        }
        
        # Get node colors - brighter and more visible
        node_colors = []
        node_shapes = []  # Different shapes for different node types
        for node in G_viz.nodes():
            node_type = G_viz.nodes[node].get('type', 'UNKNOWN')
            node_colors.append(node_type_colors.get(node_type, node_type_colors['UNKNOWN']))
            # Assign shapes: ICD9=square, CPT=circle, ATC=triangle, LAB=diamond
            if node_type == 'ICD9':
                node_shapes.append('s')  # square
            elif node_type == 'CPT':
                node_shapes.append('o')  # circle
            elif node_type == 'ATC':
                node_shapes.append('^')  # triangle
            elif node_type == 'LAB':
                node_shapes.append('D')  # diamond
            else:
                node_shapes.append('o')  # default circle
        
        # Get edge colors
        edge_colors = []
        edge_styles = []
        edge_widths = []
        for edge in G_viz.edges():
            edge_type = G_viz.edges[edge].get('edge_type', 'unknown')
            edge_colors.append(edge_type_colors.get(edge_type, edge_type_colors['unknown']))
            
            # Set line style based on edge type
            if edge_type == 'hierarchical':
                edge_styles.append('solid')
            elif edge_type == 'cooccurrence':
                edge_styles.append('dashed')
            elif edge_type == 'augmented':
                edge_styles.append('dotted')
            else:
                edge_styles.append('solid')
            
            # Set width based on weight
            weight = G_viz.edges[edge].get('weight', 1.0)
            edge_widths.append(max(0.5, min(3.0, weight / 10.0)))
        
        # Compute layout
        print(f"Computing {layout} layout...")
        if layout == 'spring':
            pos = nx.spring_layout(G_viz, k=1, iterations=50, seed=42)
        elif layout == 'circular':
            pos = nx.circular_layout(G_viz)
        elif layout == 'kamada_kawai':
            try:
                pos = nx.kamada_kawai_layout(G_viz)
            except:
                print("Kamada-Kawai layout failed, using spring layout")
                pos = nx.spring_layout(G_viz, k=1, iterations=50, seed=42)
        elif layout == 'hierarchical':
            # Try to use hierarchical layout if possible
            try:
                pos = nx.spring_layout(G_viz, k=2, iterations=100, seed=42)
            except:
                pos = nx.spring_layout(G_viz, k=1, iterations=50, seed=42)
        else:
            pos = nx.spring_layout(G_viz, k=1, iterations=50, seed=42)
        
        # Draw edges by type
        edge_groups = {}
        for i, edge in enumerate(G_viz.edges()):
            edge_type = G_viz.edges[edge].get('edge_type', 'unknown')
            if edge_type not in edge_groups:
                edge_groups[edge_type] = []
            edge_groups[edge_type].append((edge, edge_colors[i], edge_styles[i], edge_widths[i]))
        
        # Draw edges
        for edge_type, edges in edge_groups.items():
            edges_list = [e[0] for e in edges]
            colors = [e[1] for e in edges]
            styles = [e[2] for e in edges]
            widths = [e[3] for e in edges]
            
            # Draw each edge with its own style (networkx doesn't support per-edge styles easily)
            for edge, color, style, width in zip(edges_list, colors, styles, widths):
                nx.draw_networkx_edges(G_viz, pos, edgelist=[edge], 
                                     edge_color=color, style=style, 
                                     width=width, alpha=0.6, ax=ax)
        
        # Draw nodes with different shapes and brighter colors
        # Group nodes by type to draw with different shapes
        node_groups = {
            'ICD9': {'nodes': [], 'pos': {}, 'colors': []},
            'CPT': {'nodes': [], 'pos': {}, 'colors': []},
            'ATC': {'nodes': [], 'pos': {}, 'colors': []},
            'LAB': {'nodes': [], 'pos': {}, 'colors': []},
            'UNKNOWN': {'nodes': [], 'pos': {}, 'colors': []}
        }
        
        for i, node in enumerate(G_viz.nodes()):
            node_type = G_viz.nodes[node].get('type', 'UNKNOWN')
            if node_type in node_groups:
                node_groups[node_type]['nodes'].append(node)
                node_groups[node_type]['pos'][node] = pos[node]
                node_groups[node_type]['colors'].append(node_colors[i])
        
        # Draw each node type with different shapes and brighter colors
        # Note: NetworkX doesn't support different shapes per node, so we use scatter plot
        import matplotlib.patches as mpatches
        
        shape_map = {
            'ICD9': 's',  # square
            'CPT': 'o',   # circle
            'ATC': '^',   # triangle up
            'LAB': 'D',   # diamond
            'UNKNOWN': 'o'  # circle
        }
        
        for node_type, group in node_groups.items():
            if len(group['nodes']) > 0:
                # Get positions and colors for this group
                x_coords = [group['pos'][node][0] for node in group['nodes']]
                y_coords = [group['pos'][node][1] for node in group['nodes']]
                
                # Draw nodes using scatter for different shapes
                ax.scatter(x_coords, y_coords,
                         s=node_size * 1.5,  # Larger size
                         c=group['colors'],
                         marker=shape_map[node_type],
                         alpha=0.95,  # More opaque
                         edgecolors='black',  # Black border for better visibility
                         linewidths=1.0,
                         zorder=3)  # Draw nodes on top
        
        # Draw labels - always show for vocab nodes (ICD, ATC, LAB, CPT)
        labels = {}
        label_positions = {}
        
        # Helper to get node display name with prefix
        def get_node_display(node):
            node_type = G_viz.nodes[node].get('type', 'UNKNOWN')
            
            # Try to get from graphnode_vocab first
            code_str = None
            if self.graphnode_vocab:
                if node in self.graphnode_vocab:
                    code_str = str(self.graphnode_vocab[node])
            # Then try from node attribute
            if not code_str:
                code = G_viz.nodes[node].get('code', None)
                if code:
                    code_str = str(code)
                else:
                    code_str = str(node)
            
            # Add prefix based on node type for better identification
            if node_type == 'ICD9':
                # Only add prefix if not already present and not a root node
                if not code_str.startswith('ICD') and not code_str.endswith('_ROOT'):
                    return f'ICD_{code_str}'
            elif node_type == 'LAB':
                # Only add prefix if not already present and not a root/category node
                if not code_str.startswith('LAB') and not code_str.endswith('_ROOT'):
                    return f'LAB_{code_str}'
            elif node_type == 'CPT':
                # Only add prefix if not already present
                if not code_str.startswith('CPT') and not code_str.startswith('DRUG'):
                    return f'CPT_{code_str}'
            elif node_type == 'ATC':
                # Keep DRUG_ prefix if present, otherwise add ATC_ prefix
                if not code_str.startswith('DRUG') and not code_str.startswith('ATC'):
                    return f'ATC_{code_str}'
            
            return code_str
        
        # Helper to normalize for matching
        def normalize_for_match(s):
            return str(s).strip().replace('.', '').upper()
        
        # Show labels for vocab nodes (leaf nodes that are in vocab)
        vocab_nodes = set()
        vocab_nodes_normalized = set()
        if self.vocab_info:
            # Collect vocab nodes
            for vocab_type, vocab_list in self.vocab_info.items():
                for v in vocab_list:
                    vocab_nodes.add(str(v))
                    vocab_nodes_normalized.add(normalize_for_match(v))
        
        for node in G_viz.nodes():
            node_type = G_viz.nodes[node].get('type', '')
            level = G_viz.nodes[node].get('level', 999)
            degree = G_viz.degree(node)
            node_display = get_node_display(node)
            
            # Always show labels for:
            # 1. Root nodes (level 0)
            # 2. Vocab nodes (leaf nodes in vocabulary)
            # 3. High-degree nodes (degree > 3)
            should_label = False
            label_text = ""
            
            if level == 0:
                should_label = True
                label_text = str(node)[:20]  # Root node name
            else:
                # Check if node matches vocab (normalized)
                node_normalized = normalize_for_match(node)
                node_display_normalized = normalize_for_match(node_display)
                
                # Check if node or its display matches any vocab
                if (node_normalized in vocab_nodes_normalized or 
                    node_display_normalized in vocab_nodes_normalized or
                    any(node_normalized.endswith(norm) or norm.endswith(node_normalized) 
                        for norm in vocab_nodes_normalized) or
                    any(node_display_normalized.endswith(norm) or norm.endswith(node_display_normalized) 
                        for norm in vocab_nodes_normalized)):
                    should_label = True
                    # Try to find matching vocab item
                    for vocab_item in vocab_nodes:
                        if normalize_for_match(vocab_item) == node_normalized or \
                           normalize_for_match(vocab_item) == node_display_normalized:
                            label_text = str(vocab_item)[:20]
                            break
                    if not label_text:
                        label_text = node_display[:20]
                elif degree > 3:
                    should_label = True
                    label_text = node_display[:20]
            
            if should_label and label_text:
                labels[node] = label_text
                label_positions[node] = pos[node]
        
        if labels:
            # Draw labels with better visibility
            nx.draw_networkx_labels(G_viz, pos, labels, font_size=font_size + 1, 
                                  font_weight='bold', ax=ax,
                                  bbox=dict(boxstyle='round,pad=0.4', 
                                          facecolor='white', 
                                          edgecolor='black',
                                          linewidth=0.5,
                                          alpha=0.9))  # More opaque background
        
        # Create legend with shapes
        legend_elements = []
        
        # Node type legend with shapes - using correct matplotlib patch constructors
        for node_type, color in node_type_colors.items():
            if any(G_viz.nodes[n].get('type', 'UNKNOWN') == node_type for n in G_viz.nodes()):
                if node_type == 'ICD9':
                    patch = mpatches.Rectangle((0, 0), 1, 1, facecolor=color, edgecolor='black', linewidth=1)
                    patch.set_label(f'Node: {node_type}')
                    legend_elements.append(patch)
                elif node_type == 'CPT':
                    patch = mpatches.Circle((0.5, 0.5), 0.5, facecolor=color, edgecolor='black', linewidth=1)
                    patch.set_label(f'Node: {node_type}')
                    legend_elements.append(patch)
                elif node_type == 'ATC':
                    # RegularPolygon: (xy, numVertices, radius=5, orientation=0, **kwargs)
                    patch = mpatches.RegularPolygon((0.5, 0.5), 3, radius=0.5, facecolor=color, edgecolor='black', linewidth=1)
                    patch.set_label(f'Node: {node_type}')
                    legend_elements.append(patch)
                elif node_type == 'LAB':
                    # RegularPolygon for diamond: 4 vertices with 45-degree rotation
                    patch = mpatches.RegularPolygon((0.5, 0.5), 4, radius=0.5, orientation=np.pi/4, facecolor=color, edgecolor='black', linewidth=1)
                    patch.set_label(f'Node: {node_type}')
                    legend_elements.append(patch)
                else:
                    patch = mpatches.Circle((0.5, 0.5), 0.5, facecolor=color, edgecolor='black', linewidth=1)
                    patch.set_label(f'Node: {node_type}')
                    legend_elements.append(patch)
        
        # Edge type legend
        for edge_type, color in edge_type_colors.items():
            if any(G_viz.edges[e].get('edge_type', 'unknown') == edge_type for e in G_viz.edges()):
                if edge_type == 'hierarchical':
                    style = '-'
                elif edge_type == 'cooccurrence':
                    style = '--'
                elif edge_type == 'augmented':
                    style = ':'
                else:
                    style = '-'
                legend_elements.append(mpatches.Patch(color=color, label=f'Edge: {edge_type}', 
                                                     linestyle=style, linewidth=2))
        
        ax.legend(handles=legend_elements, loc='upper left', fontsize=11, 
                 framealpha=0.95, edgecolor='black', frameon=True)
        
        # Add relationships summary text box
        relationships = self.get_relationships()
        if any(len(rels) > 0 for rels in relationships.values()):
            # Build summary text
            summary_lines = ["Relationships Summary:", ""]
            for rel_type, rels in relationships.items():
                if len(rels) > 0:
                    # Get top 3 most weighted connections
                    rels_sorted = sorted(rels, key=lambda x: x.get('weight', 0), reverse=True)
                    top_rels = rels_sorted[:3]
                    summary_lines.append(f"{rel_type}: {len(rels)} connections")
                    for i, rel in enumerate(top_rels, 1):
                        node1_short = rel['node1'][:15] if len(rel['node1']) > 15 else rel['node1']
                        node2_short = rel['node2'][:15] if len(rel['node2']) > 15 else rel['node2']
                        summary_lines.append(f"  {i}. {node1_short} <-> {node2_short}")
                    if len(rels) > 3:
                        summary_lines.append(f"  ... and {len(rels) - 3} more")
                    summary_lines.append("")
            
            summary_text = "\n".join(summary_lines)
            
            # Add text box in lower right corner with better visibility
            ax.text(0.98, 0.02, summary_text, 
                   transform=ax.transAxes,
                   fontsize=9,
                   verticalalignment='bottom',
                   horizontalalignment='right',
                   bbox=dict(boxstyle='round,pad=0.6', facecolor='white', 
                           edgecolor='black', linewidth=1, alpha=0.95),
                   family='monospace')
        
        ax.set_title(f'Knowledge Graph Visualization\n'
                    f'{G_viz.number_of_nodes()} nodes, {G_viz.number_of_edges()} edges', 
                    fontsize=16, fontweight='bold', pad=20)
        ax.axis('off')
        
        plt.tight_layout()
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        print(f"Visualization saved to {output_file}")
        plt.close()
    
    def visualize_by_type(self, output_dir='graph_visualizations'):
        """Create separate visualizations for each node type"""
        os.makedirs(output_dir, exist_ok=True)
        
        node_types = set(self.G.nodes[node].get('type', 'UNKNOWN') for node in self.G.nodes())
        
        for node_type in node_types:
            print(f"\nCreating visualization for {node_type} nodes...")
            
            # Get nodes of this type and their neighbors
            type_nodes = [node for node in self.G.nodes() 
                         if self.G.nodes[node].get('type', 'UNKNOWN') == node_type]
            
            # Include neighbors
            neighbor_nodes = set(type_nodes)
            for node in type_nodes:
                neighbor_nodes.update(self.G.neighbors(node))
            
            subgraph = self.G.subgraph(neighbor_nodes)
            
            if subgraph.number_of_nodes() == 0:
                continue
            
            # Limit size
            if subgraph.number_of_nodes() > 1000:
                nodes = list(type_nodes)[:500]
                for node in nodes:
                    nodes.extend(list(self.G.neighbors(node))[:5])
                subgraph = self.G.subgraph(set(nodes))
            
            output_file = os.path.join(output_dir, f'graph_{node_type.lower()}.png')
            self._visualize_subgraph(subgraph, output_file, title=f'{node_type} Subgraph')
    
    def _visualize_subgraph(self, G_sub, output_file, title="Subgraph"):
        """Helper to visualize a specific subgraph"""
        fig, ax = plt.subplots(figsize=(16, 12))
        
        node_type_colors = {
            'ICD9': '#FF6B6B',
            'CPT': '#4ECDC4',
            'ATC': '#45B7D1',
            'LAB': '#FFA07A',
            'UNKNOWN': '#95A5A6'
        }
        
        node_colors = [node_type_colors.get(G_sub.nodes[node].get('type', 'UNKNOWN'), '#95A5A6') 
                      for node in G_sub.nodes()]
        
        pos = nx.spring_layout(G_sub, k=1, iterations=50, seed=42)
        
        nx.draw_networkx_edges(G_sub, pos, alpha=0.3, ax=ax)
        nx.draw_networkx_nodes(G_sub, pos, node_color=node_colors, 
                             node_size=100, alpha=0.8, ax=ax)
        
        ax.set_title(title, fontsize=14, fontweight='bold')
        ax.axis('off')
        
        plt.tight_layout()
        plt.savefig(output_file, dpi=300, bbox_inches='tight')
        plt.close()
        print(f"  Saved: {output_file}")


def main():
    parser = argparse.ArgumentParser(description='Visualize Knowledge Graph from pickle files')
    parser.add_argument('--graph_file', type=str, 
                       default='embed/icdatc_graph_8_20_10_256_renumbered_by_vocab.pkl',
                       help='Path to graph pickle file')
    parser.add_argument('--vocab_file', type=str, 
                       default='embed/graphnode_vocab.pkl',
                       help='Path to graphnode_vocab.pkl')
    parser.add_argument('--vocab_info_file', type=str,
                       default='embed/vocab_info.pkl',
                       help='Path to vocab_info.pkl')
    parser.add_argument('--output', type=str, default='graph_visualization.png',
                       help='Output image filename')
    parser.add_argument('--max_nodes', type=int, default=500,
                       help='Maximum nodes to visualize (if graph is too large)')
    parser.add_argument('--layout', type=str, default='spring',
                       choices=['spring', 'circular', 'kamada_kawai', 'hierarchical'],
                       help='Layout algorithm')
    parser.add_argument('--node_size', type=int, default=50,
                       help='Node size')
    parser.add_argument('--show_labels', action='store_true',
                       help='Show node labels')
    parser.add_argument('--by_type', action='store_true',
                       help='Create separate visualizations for each node type')
    parser.add_argument('--stats_only', action='store_true',
                       help='Only print statistics, do not create visualization')
    
    args = parser.parse_args()
    
    # Create visualizer
    visualizer = GraphVisualizer(
        graph_file=args.graph_file,
        vocab_file=args.vocab_file,
        vocab_info_file=args.vocab_info_file
    )
    
    # Load graph
    visualizer.load_graph()
    
    # Print statistics
    visualizer.print_statistics()
    
    # Print relationships for manual inspection
    visualizer.print_relationships()
    
    if args.stats_only:
        return
    
    # Create visualization(s)
    if args.by_type:
        visualizer.visualize_by_type()
    else:
        visualizer.visualize_graph(
            output_file=args.output,
            max_nodes=args.max_nodes,
            layout=args.layout,
            node_size=args.node_size,
            show_labels=args.show_labels
        )
    
    print("\n" + "=" * 80)
    print("Visualization complete!")
    print("=" * 80)


if __name__ == '__main__':
    main()

